apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: financial-ml-nodepool
spec:
  template:
    metadata:
      labels:
        billing-team: financial-ml
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default

      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["g5.xlarge", "c5.2xlarge", "m5.2xlarge"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand", "spot"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-west-2a", "us-west-2b", "us-west-2c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]

  disruption:
    consolidationPolicy: WhenUnderutilized
    consolidateAfter: 30s
    expireAfter: 168h  # 1 week

  limits:
    cpu: "128"
    memory: 512Gi
    nvidia.com/gpu: "8"