data_samples: 100000
max_epochs: 50
gpus_per_trial: 0
num_samples: 10

hyperparameters:
  n_estimators:
    values: [50, 100, 200]
  max_depth:
    values: [10, 20, 30, null]
  min_samples_split:
    values: [2, 5, 10]